kind: Service
apiVersion: v1
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  selector:
      matchLabels:
        app: configserver
  replicas: 3
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: mhdevacr.azurecr.io/configserver:v7
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
