kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: varena
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
spec:
  selector:
      matchLabels:
        app: configserver
  replicas: 3
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: mhdevacr.azurecr.io/configserver:v17
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_ACTIVE_PROFILE
              value: "default"
            - name: MONGO_DB_CONNECTION
              value: "mongodb://varena-cosmodb:gBLW3IJY2HsfZ98Ik5ADdxkVz6Sq8FYPrGMh8ra7SouMzw7NgQuoJC5LKG5wAjVtrJ6UyXtvwnfUktF7xngLpQ==@varena-cosmodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@varena-cosmodb@"